"""
Module: routes/export.py
Type: Effect module (route handler)
Purpose: POST /export endpoint — generate PDF from report data

Depends on:
  - effect_error.py (handle_error, make_http_error)

Used by: main.py (router registration)
Side effects: HTTP response, PDF generation
"""
from __future__ import annotations

import re
from datetime import date
from typing import Any, Dict

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel

from backend.effect_error import handle_error, make_http_error

router = APIRouter()


class ExportRequest(BaseModel):
    canvas_state: Dict[str, Any]
    report: Dict[str, Any]


def _slugify(text: str) -> str:
    """Convert text to URL-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    return re.sub(r"[\s_]+", "-", text)[:60]


def _build_report_html(canvas: Dict[str, Any], report: Dict[str, Any]) -> str:
    """Build print-ready HTML from report data."""
    process_name = canvas.get("process_name", "Untitled Process")
    context_type = canvas.get("context_type", "")
    today = date.today().strftime("%d %B %Y")

    steps_html = ""
    for sa in report.get("step_analyses", []):
        steps_html += f"""
        <tr>
          <td><strong>{_esc(sa.get('title', ''))}</strong></td>
          <td>{_esc(sa.get('task_allocation', ''))}</td>
          <td>{_esc(sa.get('risk_level', ''))}</td>
          <td>{_esc(sa.get('trust_requirement', ''))}</td>
          <td>{_esc(sa.get('handoff_needed', ''))}</td>
        </tr>
        <tr><td colspan="5" class="step-summary">{_esc(sa.get('summary', ''))}</td></tr>
        """

    risks_html = "".join(f"<li>{_esc(r)}</li>" for r in report.get("key_risks", []))
    recs_html = "".join(f"<li>{_esc(r)}</li>" for r in report.get("recommendations", []))

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page {{ size: A4; margin: 2cm; }}
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #0F1B2D; line-height: 1.6; font-size: 11pt; }}
  .report-header {{ border-bottom: 3px solid #F59E0B; padding-bottom: 1rem; margin-bottom: 2rem; }}
  .report-header h1 {{ font-size: 22pt; margin: 0 0 0.25rem; color: #0F1B2D; }}
  .report-meta {{ font-size: 9pt; color: #6B7280; }}
  h2 {{ font-size: 14pt; color: #0F1B2D; margin: 1.5rem 0 0.5rem; border-bottom: 1px solid #E5E7EB; padding-bottom: 0.25rem; }}
  p {{ margin: 0.5rem 0; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 10pt; }}
  th {{ background: #0F1B2D; color: white; padding: 0.5rem; text-align: left; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.03em; }}
  td {{ padding: 0.5rem; border-bottom: 1px solid #E5E7EB; vertical-align: top; }}
  .step-summary {{ font-size: 9pt; color: #6B7280; font-style: italic; background: #F9FAFB; }}
  ul {{ padding-left: 1.5rem; }}
  li {{ margin: 0.3rem 0; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #E5E7EB; font-size: 8pt; color: #9CA3AF; text-align: center; }}
</style>
</head>
<body>
  <div class="report-header">
    <h1>{_esc(report.get('title', process_name))}</h1>
    <div class="report-meta">{_esc(context_type)} &middot; {today} &middot; Generated by HAI Canvas</div>
  </div>

  <h2>Executive Summary</h2>
  <p>{_esc(report.get('executive_summary', ''))}</p>

  <h2>Process Overview</h2>
  <p>{_esc(report.get('process_overview', ''))}</p>

  <h2>Step-by-Step Analysis</h2>
  <table>
    <thead>
      <tr><th>Step</th><th>Allocation</th><th>Risk</th><th>Trust</th><th>Handoff</th></tr>
    </thead>
    <tbody>{steps_html}</tbody>
  </table>

  <h2>Key Risks</h2>
  <ul>{risks_html}</ul>

  <h2>Recommendations</h2>
  <ul>{recs_html}</ul>

  <h2>Trust Summary</h2>
  <p>{_esc(report.get('trust_summary', ''))}</p>

  <div class="footer">Human-AI Sensemaking Canvas &middot; Raphael Moreno / HCC Temus</div>
</body>
</html>"""


def _esc(text: str) -> str:
    """Escape HTML entities."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


@router.post("/export")
async def export_pdf(req: ExportRequest) -> Response:
    """Generate PDF from report data via WeasyPrint."""
    try:
        from weasyprint import HTML
    except (ImportError, OSError) as e:
        handle_error("ERROR", "routes.export", "export_pdf", e)
        raise HTTPException(
            status_code=501,
            detail=make_http_error("PDF_UNAVAILABLE", "PDF export requires WeasyPrint and system dependencies (pango, glib). See: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html", 501),
        )

    html_content = _build_report_html(req.canvas_state, req.report)
    process_name = req.canvas_state.get("process_name", "report")
    filename = f"hai-canvas-{_slugify(process_name)}-{date.today().isoformat()}.pdf"

    try:
        pdf_bytes = HTML(string=html_content).write_pdf()
    except Exception as e:
        handle_error("ERROR", "routes.export", "export_pdf", e)
        raise HTTPException(status_code=500, detail=make_http_error("PDF_FAILED", str(e), 500))

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
