"use strict";

/**
 * Module: effect.report.js
 * Type: Effect module
 * Purpose: Report page — fetch report from backend, render sections
 *
 * Depends on:
 *   - effect.error.js (error handling)
 *   - effect.export.js (PDF export)
 *   - config.js (API_BASE)
 *   - pure.render.js (escapeHtml)
 *
 * Used by: main.js
 * Side effects: DOM writes, HTTP requests, sessionStorage reads
 */

import { handleError } from "./effect.error.js";
import { initExport } from "./effect.export.js";
import { CONFIG } from "./config.js";
import { escapeHtml } from "./pure.render.js";

let _canvasState = null;
let _reportData = null;

function initReport() {
  _canvasState = _loadCanvasState();

  if (!_canvasState) {
    _showError("No canvas data found. Please go back and analyse a canvas first.");
    return;
  }

  const btnRetry = document.getElementById("btn-retry");
  if (btnRetry) {
    btnRetry.addEventListener("click", () => _fetchReport());
  }

  _fetchReport();
}

function _loadCanvasState() {
  try {
    const raw = sessionStorage.getItem("hai_canvas_state");
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

async function _fetchReport() {
  _showLoading();

  const url = `${CONFIG.API_BASE}/report`;

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ canvas_state: _canvasState }),
    });

    if (!res.ok) {
      const detail = await res.json().catch(() => ({ message: res.statusText }));
      throw new Error(detail.detail?.message || detail.message || `HTTP ${res.status}`);
    }

    _reportData = await res.json();
    _renderReport(_reportData);
    _showContent();

    initExport(_canvasState, _reportData);
  } catch (error) {
    handleError("effect.report", "_fetchReport", error);
    _showError(error.message);
  }
}

function _renderReport(report) {
  const title = document.getElementById("report-title");
  const meta = document.getElementById("report-meta");
  const execSummary = document.getElementById("report-exec-summary");
  const overview = document.getElementById("report-overview");
  const stepsBody = document.getElementById("report-steps-body");
  const risks = document.getElementById("report-risks");
  const recs = document.getElementById("report-recs");
  const trust = document.getElementById("report-trust");

  if (title) title.textContent = report.title || "Untitled Report";

  if (meta) {
    const contextType = _canvasState.context_type || "";
    const today = new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
    meta.textContent = `${contextType} \u00b7 ${today} \u00b7 Generated by HAI Canvas`;
  }

  if (execSummary) execSummary.textContent = report.executive_summary || "";
  if (overview) overview.textContent = report.process_overview || "";
  if (trust) trust.textContent = report.trust_summary || "";

  if (stepsBody) {
    stepsBody.innerHTML = "";
    const steps = report.step_analyses || [];
    steps.forEach((sa) => {
      const mainRow = document.createElement("tr");
      mainRow.innerHTML = `
        <td class="step-row__title">${escapeHtml(sa.title || "")}</td>
        <td>${escapeHtml(sa.task_allocation || "")}</td>
        <td>${escapeHtml(sa.risk_level || "")}</td>
        <td>${escapeHtml(sa.trust_requirement || "")}</td>
        <td>${escapeHtml(sa.handoff_needed || "")}</td>
      `;
      stepsBody.appendChild(mainRow);

      if (sa.summary) {
        const summaryRow = document.createElement("tr");
        summaryRow.innerHTML = `<td colspan="5" class="step-row__summary">${escapeHtml(sa.summary)}</td>`;
        stepsBody.appendChild(summaryRow);
      }
    });
  }

  if (risks) {
    risks.innerHTML = "";
    (report.key_risks || []).forEach((r) => {
      const li = document.createElement("li");
      li.textContent = r;
      risks.appendChild(li);
    });
  }

  if (recs) {
    recs.innerHTML = "";
    (report.recommendations || []).forEach((r) => {
      const li = document.createElement("li");
      li.textContent = r;
      recs.appendChild(li);
    });
  }
}

function _showLoading() {
  _toggle("report-loading", true);
  _toggle("report-error", false);
  _toggle("report-content", false);
}

function _showContent() {
  _toggle("report-loading", false);
  _toggle("report-error", false);
  _toggle("report-content", true);
}

function _showError(message) {
  _toggle("report-loading", false);
  _toggle("report-error", true);
  _toggle("report-content", false);

  const text = document.querySelector(".report-error__text");
  if (text) text.textContent = message || "Failed to generate report.";
}

function _toggle(id, show) {
  const el = document.getElementById(id);
  if (!el) return;
  el.hidden = !show;
}

export { initReport };
